feat(firebase): supports `firebase` (#212)
* feat(supabase): signed url

* refactor: remove fileUrl field for db

* remove: getPluginEnv

* feat: supabase edge bucket name

* fix: supabase

* fix: types

* fix: deps

* fix: database plugin core

* fix: types

* chore: pnpm bump

* fix: clear DerivedData

* fix: ios

* fix: console

* fix: use sync external store compat

* fix: ios ci 14

* fix: supabase

* feat(ios): bundleUrl debug mode user setting

* fix(supabase): edge-functions

* fix: ktlint

* chore: approve deps

* fix: schema

* fix: channel

* docs: getChannel()

* feat(example): format date

* feat(cloudflare): jwt baesd download

* fix: 60

* fix(cloudflare): private

* feat(js): jwt signed url

* fix: compat

* fix: header

* fix: ci

* fix: body

* fix: ci

* fix: ci

* fix: test

* fix: update message

* fix: ci

* feat: aws origin-request and use jwt signed

* fix: jwt secret

* feat(aws): jwt based signed

* fix: aws

* fix(aws): cache 1m

* fix: s3Database

* fix: lint

* feat(firebase): add serverless

* feat(firebase): create getUpdateInfo function

* refactoring(firebase): modify logic

* refactoring(firebase): modify logic

* refactoring(firebase): remove 1-depth in serverless(firebase in firebaes)

* chore(firebase): remove unused dependencies

* feat(firebase): create firebase init(login, projects, web app)

* feat(firebase): add serverless, init

* chore(firebase): push pnpm-lock for fix CI error

* refactoring(firebase): modify directory path, add spinner to terminal

* chore(firebase): modify dependencies, seperatly install

* refact(firebase): bundling firebase functions

* fix(firebase): fix index directory

* feat(firebase): Make users choice region to deploy

* feat(firebase): add testcase for getUpdateInfo
Add ability to skip deploy for users already init
Add firestore indexes for use with query statements in getUpdateInfo

* refact(firebase): automatically run firebase Emulator for test

* refact(firebase): modify directory
add 'pnpm' for user's env

* refact(firebase): rollback ex dir

* refact(firebase): reduce requests from 3 to 2 and overhead

* refact(firebase): remove dependency

* fix: migrator

* fix: dry run

* fix: migrator

* feat: migrator

* fiix

* fix

* feat(firebase): match db, storage to new spec

* fix: spec test

* fix: s3 migrator

* fix: migrator

* fix: migrations

* fix: data

* fix: 주석

* chore: picocolors

* fix: lock

* fix: use cdn

* fix: cache

* fix: test

* fix: test

* fix: env

* fix: qetUpdateInfo

* fix: info

* fix: console

* fix: types and key

* fix: maybe

* feat(firebase): satisfy getUpdateInfo new spec for 0.13.0

* fix(firebase): add firebase-admin for getUpdateInfo type

* fix(firebase): fix CI error

* fix: console

* fix: filter

* fix(firebase): fix emulator CI error

* feat(firebase): add serverless for making download URL

* fix: update lambda

* fix: s3Database

* fix: cloudfront

* fix: cache

* fix: init

* fix: s3 database

* feat(firebase): making URL with JWT

* feat(firebase): make rules private(db, storage)

* fix: cache

* fix: always miss

* fix: cache

* feat(firebase): serverless function with security, JWT

* feat(firebase): add rules for private

* feat(firebase): add spec for security

* refact(firebase): make only one serverless functions with Hono

* refact(firebase): remove regacy

* feat(firebase): make JWT with secretKey using crypto

* feat: cloudfront signedurl

* fix: dev

* fix: permission

* fix: test

* fix: ssm

* refact(firebase): fix URL for convetion

* fix(firebase): conflict

* fix(firebase): testcase

* refact(firebase): init to firebase repo

* fix: add review content

* fix: functions cannot find module (tsup NoExternal)

* refact: edit indexes only id descending

* refact: remove indexing, add confirm for init

* refact: use app to admin (firebase SDK)

* refact: remove unnecessary init

* refact: add indexing for db

* refact:edit init for getting json path

* fix: edit camel to snake(for firebaseSDK config)

* feat:add db testcase

* refact(firebase): import only one fs

* refact(firebase): edit update server logic light

* refact(firebase): edit typeerror, init upper case

* refact(firebase): make createApp (connectiong hono) for abstraction

* refact(firebase): delete middleware, dependencies

* fix: deploy error, add currying in deploy index

* fix: CI emulator error

* refact(firebase): sync ex(v.0.77.0) to main

* chore: pnpm i

* fix: reivew

* fix

* perf: getUpdateInfo

* fix: log

* fix: stderr

* fix: or

* fix: comment

* fix: unusing log

* fix: package

* fix: error handling

* fix: using p log

* fix: fail

* fix: select

* fix: without task

* fix: noExternal

* fix: error

* fix: url

* fix: types

* fix: dts

* fix: deps

* fix: index

* fix: withSigend

* fix: privare false

* fix: already index merge

* fix: merge original index

* fix: not 1

* fix: test case

* fix: test

* fix: index

* fix: jwt

* fix: target app version

* fix: inject credential

* fix: rollback

* fix: cert

* fix: firebase create

* fix: next step

* feat: dx

* fix: gcloud login

* feat: firebase-functions v2

* fix: bucket

* fix: end

* fix: hide

* fix: detail

* fix: detail

* fix: unused files

* fix: folder

* fix: url

* refact(firebase): edit functions v1 -> v2 in json

* fix: test

* fix: server

* fix: comment

* fix: test

* fix: test

* fix: test

* fix:test

* fix: cwd

* fix: test

* fix: for of

* fix: bucket

* fix: default

* fix: word

* fix: types

* fix: types

* fix: keyword

* fix: config

* fix: indent

---------

Co-authored-by: Sungyu Kang <gron1gh1@gmail.com>